/* ================================================================
   dom.js — Document Object Model references
   ================================================================ */

const html = document.documentElement;
export const el = {
  html, tabs:[...document.querySelectorAll("[data-tab-target]")], pages:[...document.querySelectorAll(".page")],
  brandHome:document.getElementById("brandHome"), topbar:document.getElementById("topbar"),
  fullscreenBtn:document.getElementById("fullscreenBtn"),
  keyboardShortcutsBtn:document.getElementById("keyboardShortcutsBtn"),
  shortcutsDialog:document.getElementById("shortcutsDialog"),
  closeShortcuts:document.getElementById("closeShortcuts"),
  toast:document.getElementById("toast"), bgFx:document.getElementById("bgFx"),
  greetingEyebrow:document.getElementById("greetingEyebrow"),
  greetingName:document.getElementById("greetingName"),
  digitalClock:document.getElementById("digitalClock"),
  ckHH:null, ckMM:null, ckSS:null, ckSuffix:null,
  analogClock:document.getElementById("analogClock"),
  acHourHand:document.getElementById("acHourHand"), acMinHand:document.getElementById("acMinHand"),
  acSecHand:document.getElementById("acSecHand"), acMarkers:document.getElementById("acMarkers"),
  flipClock:document.getElementById("flipClock"),
  flipH1:document.getElementById("flipH1"), flipH2:document.getElementById("flipH2"),
  flipM1:document.getElementById("flipM1"), flipM2:document.getElementById("flipM2"),
  flipS1:document.getElementById("flipS1"), flipS2:document.getElementById("flipS2"),
  faceButtons:[...document.querySelectorAll("[data-face]")],
  dateLabel:document.getElementById("dateLabel"),
  timezoneLabel:document.getElementById("timezoneLabel"),
  nextAlarmLabel:document.getElementById("nextAlarmLabel"),
  audioStatus:document.getElementById("audioStatus"),
  unlockAudio:document.getElementById("unlockAudio"),
  alarmForm:document.getElementById("alarmForm"), alarmTime:document.getElementById("alarmTime"),
  alarmLabel:document.getElementById("alarmLabel"), alarmSound:document.getElementById("alarmSound"),
  alarmRepeat:document.getElementById("alarmRepeat"), alarmList:document.getElementById("alarmList"),
  quickOne:document.getElementById("quickOne"), quickTen:document.getElementById("quickTen"),
  quickThirty:document.getElementById("quickThirty"),
  quickTestAlarm:document.getElementById("quickTestAlarm"),
  testAlarmSound:document.getElementById("testAlarmSound"),
  timerDisplay:document.getElementById("timerDisplay"),
  timerRingArc:document.getElementById("timerRingArc"),
  timerHours:document.getElementById("timerHours"),
  timerMinutes:document.getElementById("timerMinutes"), timerSeconds:document.getElementById("timerSeconds"),
  startTimer:document.getElementById("startTimer"), pauseTimer:document.getElementById("pauseTimer"),
  resetTimer:document.getElementById("resetTimer"),
  startThreeSecondTimer:document.getElementById("startThreeSecondTimer"),
  timerPresets:[...document.querySelectorAll("[data-timer-preset]")],
  testTimerSound:document.getElementById("testTimerSound"),
  pomodoroToggle:document.getElementById("pomodoroToggle"),
  pomodoroSessions:document.getElementById("pomodoroSessions"),
  pomodoroSettings:document.getElementById("pomodoroSettings"),
  pomodoroWork:document.getElementById("pomodoroWork"), pomodoroBreak:document.getElementById("pomodoroBreak"),
  pomodoroLongBreak:document.getElementById("pomodoroLongBreak"),
  pomodoroRounds:document.getElementById("pomodoroRounds"),
  timerPomodoroLabel:document.getElementById("timerPomodoroLabel"),
  timerInputs:document.getElementById("timerInputs"),
  swHours:document.getElementById("swHours"), swMin:document.getElementById("swMin"),
  swSec:document.getElementById("swSec"), swCs:document.getElementById("swCs"),
  swSplitDelta:document.getElementById("swSplitDelta"),
  startStopwatch:document.getElementById("startStopwatch"),
  lapStopwatch:document.getElementById("lapStopwatch"),
  resetStopwatch:document.getElementById("resetStopwatch"),
  lapList:document.getElementById("lapList"), exportLaps:document.getElementById("exportLaps"),
  addWorldClock:document.getElementById("addWorldClock"),
  worldAddPanel:document.getElementById("worldAddPanel"),
  worldAddForm:document.getElementById("worldAddForm"),
  worldTimezone:document.getElementById("worldTimezone"),
  worldLabel:document.getElementById("worldLabel"),
  cancelWorldAdd:document.getElementById("cancelWorldAdd"),
  worldClockGrid:document.getElementById("worldClockGrid"),
  worldEmptyHint:document.getElementById("worldEmptyHint"),
  displayName:document.getElementById("displayName"),
  greetingStyle:document.getElementById("greetingStyle"),
  customMotto:document.getElementById("customMotto"),
  themeCards:[...document.querySelectorAll("[data-theme-pick]")],
  layoutSeg:document.querySelector('[data-seg="layout"]'),
  fontScaleSeg:document.querySelector('[data-seg="fontScale"]'),
  accentSwatches:document.getElementById("accentSwatches"),
  clockCustomColorToggle:document.getElementById("clockCustomColorToggle"),
  clockColorInputs:[document.getElementById("clockColor1"),document.getElementById("clockColor2"),document.getElementById("clockColor3")],
  fxToggle:document.getElementById("fxToggle"), scanlinesToggle:document.getElementById("scanlinesToggle"),
  grainToggle:document.getElementById("grainToggle"),
  topbarAutoHideToggle:document.getElementById("topbarAutoHideToggle"),
  hourToggle:document.getElementById("hourToggle"), secondsToggle:document.getElementById("secondsToggle"),
  blinkToggle:document.getElementById("blinkToggle"), dateFormat:document.getElementById("dateFormat"),
  defaultAlarmSound:document.getElementById("defaultAlarmSound"),
  defaultTimerSound:document.getElementById("defaultTimerSound"),
  volumeRange:document.getElementById("volumeRange"), mutedToggle:document.getElementById("mutedToggle"),
  ambientBtns:[...document.querySelectorAll("[data-ambient]")],
  ambientVolume:document.getElementById("ambientVolume"),
  resetSettings:document.getElementById("resetSettings"),
  ringDialog:document.getElementById("ringDialog"), ringKind:document.getElementById("ringKind"),
  ringTitle:document.getElementById("ringTitle"), ringDetail:document.getElementById("ringDetail"),
  stopRing:document.getElementById("stopRing"), snoozeRing:document.getElementById("snoozeRing"),
};

if (el.digitalClock) {
  el.ckHH=el.digitalClock.querySelector(".ck-hh");
  el.ckMM=el.digitalClock.querySelector(".ck-mm");
  el.ckSS=el.digitalClock.querySelector(".ck-ss");
  el.ckSuffix=el.digitalClock.querySelector(".ck-suffix");
}
